# Generated by Django 5.0 on 2023-12-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgeory',
            new_name='Category',
        ),
    ]
